services:
    # use https://github.com/3rdpartyeve/phealng for xml api call and caching
#    eve_nomad.pheal:
#        class: Tribalpixel\EveNomadBundle\Service\PhealService
#        arguments: [%eve_nomad.parameters%] 
        
#    eve_nomad.db:
#        class: Tribalpixel\EveNomadBundle\Service\EveDatabaseService
#        arguments: ['@doctrine.dbal.eve_connection','@doctrine.dbal.default_connection']  

#    eve_nomad.parser:
#        class: Tribalpixel\EveNomadBundle\Service\ParserService
#        arguments: ['@eve_nomad.db'] 